### ISSUE TITLE
arezoooye nasb

### ISSUE THREAD

**Issue by nikoobehjati** [Azumi67/WGDashboard_Persian#4]
daaaah bar roye daaaah ta server test  kardam   faght safheye login ro didam bad login in miyomad .... har kar kardam nashod   yek mah har rooooooz talash kardam 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Azumi67** [comment]
ببینید مشکل internal error می‌تونه به دلایل متفاوتی باشه . مثلا اینترفیس رو در کانفیگ وایرگارد اشتباه وارد کرده باشید . وارپ فعال داشته باشید . سرویس داشبورد از دو پورت استفاده کنه یا آی‌پی وایرگارد با آی‌پی پرایوت داخلی تداخل داشته باشه . دلایل زیادی داره وگرنه خیلی راحت نصب میشه .
