### ISSUE TITLE
تداخل با x-ui

### ISSUE THREAD

**Issue by t-51** [Azumi67/WGDashboard_Persian#5]
سلام وقت بخیر 
ببخشید یک سوالی که دارم این اسکریپت با x-iu مشکل داره ؟
من اونو نصب دارم پنل اینو میزنم بالا نمی یاد اصلا !

**Comment by Azumi67** [comment]
سلام نباید مشکلی باشه. ممکنه کمی با warp wireguard مشکل ساز باشه فقط.
