### ISSUE TITLE
عدم اتصال

### ISSUE THREAD

**Issue by Ten10vpn** [Azumi67/WGDashboard_Persian#8]
سلام پنل زیباتونو نصب کردم خیلی عالیه.
کانفیگی که میسازم انتقال اطلاعات و توی برنامه وایرگارد نشون میده ولی عملا وصل نیستم چون مثلا داخل تلگرام در وضعیت کانکتینگ هستم.

![Screenshot_20240906-173216_WireGuard](https://github.com/user-attachments/assets/7870ef18-787d-4bba-b230-27af80a881db)

**Comment by Azumi67** [comment]
سلام. لطفا با تانل frp هم تست کنید. لوکال هم تست نمایید. میتونه به دلیل تانل شما هم باشه که با عوض کردنش مشکل حل میشه
